### ISSUE TITLE
Errors on two charged molecules

### ISSUE THREAD

**Issue by larsbratholm** [jensengroup/molcalc#11]
Error when trying to do calculations on http://molview.org/?cid=22385494 (NH3+CHO) and http://molview.org/?cid=19073436 (NHCHO-)

Warning: file_get_contents(http://cactus.nci.nih.gov/chemical/structure/C(%3DO)%5BNH3%5D/iupac_name) [function.file-get-contents]: failed to open stream: HTTP request failed! HTTP/1.1 404 NOT FOUND in /srv/www/molcalc/methods/initialize/initialize.php on line 53
71dcd0472db547597459b8ed463325bb

**Comment by charnley** [comment]
Error originated on cactus name dependency. Fixed on both live and development version.
