### ISSUE TITLE
Get error when trying to calculate

### ISSUE THREAD

**Issue by pincher-chen** [jensengroup/molcalc#14]
$ ls data/
3ccab5ef041634fc1b7db4ad897e96b5  61147a6682500baa0150a29b9b1b340b
4cbc93d6590db82284385d1d7ac8b805  ba9091c120118ad126ef24fc87bfc354

$ ls data/61147a6682500baa0150a29b9b1b340b/
61147a6682500baa0150a29b9b1b340b.dat  coordinates_jmol.xyz  molecule.db
61147a6682500baa0150a29b9b1b340b.inp  coordinates.mol2      thumbnail.png
61147a6682500baa0150a29b9b1b340b.log  coordinates.xyz

$ tail  ~/sf_install/apache/logs/error_log
cp 3ccab5ef041634fc1b7db4ad897e96b5.inp /home/dokuwiki/www/molcalc/data/3ccab5ef041634fc1b7db4ad897e96b5/3ccab5ef041634fc1b7db4ad897e96b5.F05
unset echo
/home/dokuwiki/sf_box/gamess/ddikick.x /home/dokuwiki/sf_box/gamess/gamess.00.x 3ccab5ef041634fc1b7db4ad897e96b5 -ddi 1 1 dokuwiki -scr /home/dokuwiki/www/molcalc/data/3ccab5ef041634fc1b7db4ad897e96b5
unset echo
ls: No match.
ls: No match.
ls: No match.
1 molecule converted
16 audit log messages 
1 molecule converted
20 audit log messages 
1 molecule converted
27 audit log messages 
1 molecule converted
15 audit log messages 
1 molecule converted
15 audit log messages 
[Thu Jun 08 23:31:42.978000 2017] [:error] [pid 8786:tid 140065820882688] [client 172.16.3.21:54227] PHP Warning:  get_headers(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /home/dokuwiki/www/molcalc/methods/initialize/initialize.php on line 20, referer: http://172.16.11.179:8008/molcalc/
[Thu Jun 08 23:31:42.978155 2017] [:error] [pid 8786:tid 140065820882688] [client 172.16.3.21:54227] PHP Warning:  get_headers(): Failed to enable crypto in /home/dokuwiki/www/molcalc/methods/initialize/initialize.php on line 20, referer: http://172.16.11.179:8008/molcalc/
[Thu Jun 08 23:31:42.978307 2017] [:error] [pid 8786:tid 140065820882688] [client 172.16.3.21:54227] PHP Warning:  get_headers(http://cactus.nci.nih.gov/chemical/structure/C%5BSiH3%5D/iupac_name): failed to open stream: operation failed in /home/dokuwiki/www/molcalc/methods/initialize/initialize.php on line 20, referer: http://172.16.11.179:8008/molcalc/
[Thu Jun 08 23:31:44.744321 2017] [:error] [pid 8786:tid 140065820882688] [client 172.16.3.21:54227] PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /home/dokuwiki/www/molcalc/methods/initialize/initialize.php on line 53, referer: http://172.16.11.179:8008/molcalc/
[Thu Jun 08 23:31:44.744355 2017] [:error] [pid 8786:tid 140065820882688] [client 172.16.3.21:54227] PHP Warning:  file_get_contents(): Failed to enable crypto in /home/dokuwiki/www/molcalc/methods/initialize/initialize.php on line 53, referer: http://172.16.11.179:8008/molcalc/
[Thu Jun 08 23:31:44.744391 2017] [:error] [pid 8786:tid 140065820882688] [client 172.16.3.21:54227] PHP Warning:  file_get_contents(http://cactus.nci.nih.gov/chemical/structure/C%5BSiH3%5D/iupac_name): failed to open stream: operation failed in /home/dokuwiki/www/molcalc/methods/initialize/initialize.php on line 53, referer: http://172.16.11.179:8008/molcalc/
1 molecule converted
46 audit log messages 
[Thu Jun 08 23:31:44.930610 2017] [:error] [pid 8786:tid 140065810392832] [client 172.16.3.21:54227] PHP Parse error:  syntax error, unexpected 'else' (T_ELSE) in /home/dokuwiki/www/molcalc/views/pages/calculation.php on line 119, referer: http://172.16.11.179:8008/molcalc/

**Comment by charnley** [comment]
The error is from contacting cactus server (trying to get a name from smiles). This is not an issue in the new molcalc server.
