### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by vladislavivanistsev** [jensengroup/molcalc#15]
I am following the README, yet can not run the calculations. The health check tells that everything is alright. However, Molecule List and About are not found. Pressing the "Calculate Properties" button gets stuck at "preparing molecule for property calculation...". There is something missing that I do not see in the README. Could you please point to that?

For instance, the "GAMESS Note" in the README is not clear. At least for a new user of both molcalc and GAMESS. Should the "data" (tmpfolder) be the same as "SCR" in rungms?

Ubuntu 17.10, PHP5 / Apache2, GAMESS 2018. All fresh and working.

**Comment by charnley** [comment]
Since "About" is getting a 404, I suspect the "rewrite" module is not turned on. It should be checked by the health_check.php, but can you double check that for me?
If you use Chrome then you can open the "Developer toolbar" (F12) to see in the console why the "calculate property" is stuck, but I'm guessing it is the same problem as "about".

regarding folders; no, it should not be the same,
- the datafolder (tmpfolder in settings) is where to store the log files for the molcalc (should be in the molcalc folder)
- the "scr" folder is where to put tempoary GAMESS files used for the calculation (if used locally, use the /tmp folder)

**Comment by vladislavivanistsev** [comment]
You are right, although the module rewrite is enabled, the reason why GAMESS does not start is due to 404 error. Chrome console shows: POST http://xxx.xx.x.xxx/initialize/initialize 404 (Not Found)
Might the reason be in the address? I have only an IP address.
Herewith, http://xxx.xx.x.xxx/views/pages/about.php opens. Also, editor.php, but not calculation.php.

**Comment by charnley** [comment]
No, you should be able to open molcalc fine with a IP address. I would focus on getting the "about" page to load up, as I still think the problem is somehow the rewrite module in apache is not turned on. 
Do you have "AllowOverride All" for the molcalc directory in the apache setup?
I would also recommend looking at "phpinfo();" to see if it is disabled.
https://stackoverflow.com/questions/3772892/phpinfo-mod-rewrite

**Comment by vladislavivanistsev** [comment]
You are right. I have to change setting in /etc/apache2/ from "AllowOverride None" to "AllowOverride All". Then executing "service apache2 restart". I believe this could be added to the README.
The about page works.
Something is still wrong with gamess. Inputs are not copied to the scr folder. In the README, there is a mention of rungms_molcalc. Should I change the owner of privileges of the scr folder of something like that?

**Comment by charnley** [comment]
rungms will probably not work by default, as www-user does not have a $HOME. You need to change the rungms to exclude that. If you are using /tmp as scr folder, then www-data should have privileges to use it.

**Comment by vladislavivanistsev** [comment]
The input file in /data/XXX have permission "-rw-r--r--" (644). Is it right?
The resulting log-file looks like that:
"""
...
GAMESS temporary binary files will be written to /tmp
GAMESS supplementary output files will be written to /tmp
Copying input file 1bf7caa230106a3bd0689cc7be466332.inp to your run's scratch directory...
"""
When I change the privileges and run gamess manually, the calculation runs normally leading to a much longer log.
I have tried various combinations of privileges and ownerships without success. For the benefit of all potential users, could you please explain the logic behind the privileges? Is it so  that www-data has the rights to write to data, it executes gamess in /tmp and writes the log to data/XXX?

**Comment by charnley** [comment]
Yeah, I probably need to update the installation guide a bit.

Regarding data/*, yes, the user `www-data` needs to have write access to save log files (`www-data` is the apache web user).

Regarding rungms, which is the GAMESS executable, it is written a bit overly complicated and you need to hack it so it does not use environmental variables unavailable to `www-data` (i.e. the `$HOME` variable). This is why it works with your user. To test it properly you can `sudo su www-data` and try to to run GAMESS.

**Comment by vladislavivanistsev** [comment]
After resolving all problems, I would be happy to commit updates to the README.
Several modifications allowed one step forward.
First, I have commented, although there is no .gmsrc:
#if (-e $HOME/.gmsrc) then
#   echo "reading your own $HOME/.gmsrc"
#   source $HOME/.gmsrc
#endif
Second, due to problems wtih /tmp and decided to use explicit "scr" folder with 777 permissions, like the "data".
set SCR=/home/user/gamess/scr
set USERSCR=/home/user/gamess/scr
#set SCR=/var
#set USERSCR=/var

**Comment by vladislavivanistsev** [comment]
The next problem is that "calculation" show nothing. Neither /calculation nor /calculation/hash.
The html code is broken, it ends as
"""

  <article>
  <section class="container">
"""
The data/hash folder contains necessary files, for example:
-rw-r--r-- 1 www-data www-data   471 Mar 11 00:24 8abc4396b8302086cb7ffef6413b2eac.inp
-rw-r--r-- 1 www-data www-data 62290 Mar 11 00:24 8abc4396b8302086cb7ffef6413b2eac.log
-rw-r--r-- 1 www-data www-data   349 Mar 11 00:24 coordinates_jmol.xyz
-rw-r--r-- 1 www-data www-data   599 Mar 11 00:24 coordinates.mol2
-rw-r--r-- 1 www-data www-data   308 Mar 11 00:24 coordinates.xyz
-rw-r--r-- 1 www-data www-data    76 Mar 11 00:24 molecule.db
-rw-r--r-- 1 www-data www-data  2195 Mar 11 00:24 thumbnail.png

Do you have ideas, what could be the reason?

**Comment by vladislavivanistsev** [comment]
In the calculation.php the order of the lines is different:
```
<section class="body">
    <section class="container">
<!-- CONTENT -->
```
Could you please hint where do these lines come from?
```
<!-- Content -->
<article>
<section class="container">
```

**Comment by vladislavivanistsev** [comment]
The error is located somewhere in between these lines:
```
<?php
    foreach($calculationTypes as $calculationType => $calculationName):
    $exists = is_dir($calculationType);
?>

    <div class="calculationtype <?php print $calculationType ?>">

        <?php if($exists): ?>

            <?php
                chdir($calculationType);
                require(CALPATH.'/'.$calculationType.'/view.php');
                chdir('..');
            ?>

        <?php else: ?>

            <p><a class="button calculate-now">Calculate</a></p>

        <?php endif; ?>


        <div class="clean"></div>
    </div>

<?
    endforeach;
?>
```
Apache log hints to "PHP Parse error:  syntax error, unexpected 'else' (T_ELSE) in /var/www/molcalc/views/pages/calculation.php on line 119". This line is "<?php else:?>".
Could you please check if calculation.php is the same on your working server molcalc.org?

**Comment by vladislavivanistsev** [comment]
Hurray! There is an error. 
Should be
<?php
    endforeach;
?>

**Comment by charnley** [comment]
Ah, right, the php parser moved away from `<? ?>` being usable in code. for some reason.
Is everything working now then?

I will accept the pull requests.
