### ISSUE TITLE
Error message opening Molecule List tab

### ISSUE THREAD

**Issue by andrejrenard** [jensengroup/molcalc#18]
![image](https://user-images.githubusercontent.com/12773344/52192765-03546980-284c-11e9-9133-179009258629.png)

**Comment by charnley** [comment]
The error is there when the exact moment someone is doing a molcalc calculation, but has not finished yet, so `molecule.db` is not generated again. But I actually think that the molecule list is going to disappear in the new version, as it becomes quite a large list (currently 35K molecules).

@andrejrenard unless you need it for something specific?
