### ISSUE TITLE
Diatomic molecules

### ISSUE THREAD

**Issue by g-orbital** [jensengroup/molcalc#21]
The new beta version struggles to calculate the properties of simple diatomic molecules such as Li2, C2, and N2. 

The Li2 calculation fails to compile because it can't determine the solvation properties.
The N2 calculation does not compile unless Molcalc adds hydrogens and processes it as N2H4.
The C2 calculation does not compile unless Molcalc adds hydrogens and processes it as C2H4.

**Comment by charnley** [comment]
You are correct. It assumed you were using the 2D builder by default if no Hydrogens was present. This has been fixed now.
