### ISSUE TITLE
Is it working for a single atom? Not a molecule

### ISSUE THREAD

**Issue by coldenisey** [jensengroup/molcalc#22]
For example if I want to calculate the orbital energy of H atom, which is -13.6eV for n=1
Or O atom etc

**Comment by charnley** [comment]
MolCalc only supports restricted HF, so it will support [O -2].
http://beta.molcalc.org/calculations/d60d05ca148ff23c7ab20b3991cb38ac#/orbitals

However, for [H -1] there is a bug it seems. I will fix that.

**Comment by coldenisey** [comment]
Thanks. What HF stands for?

**Comment by charnley** [comment]
Hatree-Fock. https://en.wikipedia.org/wiki/Hartree%E2%80%93Fock_method

The method used in MolCalc are either semi-empirical methods (PM3) or hatree-fock for the molecular orbitals.

**Comment by coldenisey** [comment]
good to know
