### ISSUE TITLE
Solvation calcs fail for halogens

### ISSUE THREAD

**Issue by chemimprov** [jensengroup/molcalc#24]
See the following example for 2-fluoropropane.

![image](https://user-images.githubusercontent.com/63161461/95110079-7ee67800-070b-11eb-9bb6-ebbb043b249d.png)

**Comment by charnley** [comment]
Hi Chemimprov. The issues seem to work on beta.molcalc.org.

http://beta.molcalc.org/calculations/4ac881cb460d5c72f18f5037d7fe5f2d#/solvation

I will move molcalc.org to the new version as soon as I have a weekend to do it, but it might be in a month time. The beta URL will continue to work after the move.
