### ISSUE TITLE
Atomic orbital calculations bug in beta version

### ISSUE THREAD

**Issue by g-orbital** [jensengroup/molcalc#26]
Atomic orbital calculations for single atoms with an even number of electrons do not compile for atoms such as Mg like they do in the old version.

When the orbital calculations do compile, they default to a molecule that wasn't queried. For example, in the case of a C atom, the atomic orbital calculation defaults to a calculation for CH4 molecular orbitals.

**Comment by charnley** [comment]
Were you trying to calculate C with a -4 charge?

**Comment by charnley** [comment]
Confirmed bug. Will look into it.

**Comment by g-orbital** [comment]
No, I submitted a job for a neutral C atom.

**Comment by charnley** [comment]
Hi @g-orbital , the issue has been resolved in the newest commits and will be pushed to beta URL. Thanks for reporting it, please submit more when you find it!
