### ISSUE TITLE
Site Not Working

### ISSUE THREAD

**Issue by goethepamuk** [jensengroup/molcalc#30]
When I try to look for an molecule such as HCl, it says that I don't have internet connection and says to me to wait and try again. However, I have internet connection. Can you please fix this issue, I need to use the website very urgently.

**Comment by charnley** [comment]
The server was stalled because someone had submitted a very complicated molecule that took all the resources. The server is up again. 

I will add a timeout for calculations.

**Comment by goethepamuk** [comment]
Thanks a lot for fixing the issue you really saved my life.
