### ISSUE TITLE
Again the website isn't working.

### ISSUE THREAD

**Issue by goethepamuk** [jensengroup/molcalc#31]
Hello, I wrote yesterday that the website wasn't working and you fixed it. I think it is broken again can fix it? Thank you.

**Comment by charnley** [comment]
It seems like someone is using molcalc as a submit system for some research with Br. Flooding the server with calculations. Is this you?

**Comment by goethepamuk** [comment]
No, I'm sumbitting molecules with Hcl, hclo...

**Comment by charnley** [comment]
@goethepamuk Thanks, those should not be a problem for the system to handle. :) I will try to find a fix to avoid having the system stalled. Unfortunately, I cannot promise that molcalc won't go down again if the person who is submitting large Br clusters keeps it on. Please ping me in this thread when molcalc is stalling, and I'll restart it until I've made a fix. Sorry for the inconvenience you are having. 

Someone is requesting several molecules with 5+ Bromine per minute.

**Comment by goethepamuk** [comment]
Ok thanks a lot. Also, I had a very quick question. I'am Trying to look for the HClO2 and I write it into the search bar but it is stuck in  saying "Converting O[Cl]=O". Do you know why this happens?

**Comment by charnley** [comment]
The search bar is using cactus https://cactus.nci.nih.gov/chemical/structure to convert the molecule. It could be your internet connection to that service. Try to refresh the website. Or draw the molecule yourself : )

**Comment by goethepamuk** [comment]
Okay, thanks a lot :). And one last thing, I do this for research but I'am confused in one point. What is solvation energy. I looked at the internet but I couldn't find an exact answer. Do you have an link or an book suggestion to explain it?

**Comment by charnley** [comment]
You'll need to read some books on Physical Chemistry, Computational Chemistry and Quantum Chemistry. Would be fitting to advertise Molecular Modeling Basic by Jan Jensen

**Comment by charnley** [comment]
changelog: Implemented timeout fix for multiprocessing and added error handling to avoid stalling the processes
