### ISSUE TITLE
No OSS License for MolCalc

### ISSUE THREAD

**Issue by sseyler** [jensengroup/molcalc#37]
I noticed that the About page on molcalc.org states "Yes, MolCalc is distributed through GitHub under the GPL license," but there is no license in the repo. I saw a LICENSE file in the MolCalc-1.3 repo, though there does not appear to be a full GPL license there either.

If the project is intended to be distributed under a version of GPL, would it be possible to have a proper GPL license file added? That way, I can ensure that I'm using and extending MolCalc under the proper license.

Thanks!

**Comment by charnley** [comment]
Added MIT license. Hope this clears up everything.

**Comment by sseyler** [comment]
It does! Thank you again.
