### ISSUE TITLE
Differences in properties depending on how the compound is feeded

### ISSUE THREAD

**Issue by fjvico** [jensengroup/molcalc#40]
When computing properties for `C(=N)O` the energy of heat of formation is different if the structure is drawn vs. feeding the SMILES code. Is it a bug, or does MolCalc apply different settings depending on how the compound is specified?

**Comment by fjvico** [comment]
Assuming MolCalc uses GAMESS' G3MP2 composite method, this [log](http://myweb.liu.edu/~nmatsuna/gamess/tests/exam43.log) shows the result for methane, consistent with the $\mathrm{-74.6 kJ mol^{-1}}$ in [Wikipedia](https://en.wikipedia.org/wiki/Standard_enthalpy_of_formation#Aliphatic_hydrocarbons), but the result that MolCalc shows is rather different: $\mathrm{-54.45 kJ mol^{-1}}$.

**Comment by charnley** [comment]
Can you post the URL's for the calculation, when I try I get the same HoF

- http://molcalc.org/calculations/22a5eafedf1c947be244494ca4224815 (from smiles)
- http://molcalc.org/calculations/c7b374ae9c90c47f41a3fc24da515b11 (from 3d drawn)

There is not difference in the calculation type, could only be the conformer difference. 
Did you maybe add some charges to the compound?

> Assuming MolCalc uses GAMESS' G3MP2

We are not using MP2. You can read about the method used at DOI: 10.1021/ed400164n

Please note:

> MolCalc is designed for teaching as opposed to research - specifically for assignments in which students build their own molecules and estimate their own molecular properties. It is designed to run fast and therefore estimated molecular properties will not match experimental values exactly, and in some cases be quite different.

**Comment by fjvico** [comment]
Please, find here the [link](https://molcalc.org/calculations/2cc816a28d185fb141fd9675e01f95a8) to the results obtained. The molecule was drawn in 2D mode, I assume that you can retrieve the original molecule from the results page.

**Comment by charnley** [comment]
That is a conformer difference. Those are two different local minima based on the direction of the Hydrogen alcohol group.

![Screenshot 2023-05-15 at 10 53 02](https://github.com/jensengroup/molcalc/assets/2011468/544a04f5-855f-450d-9a8e-61f6eea7b28e)
![Screenshot 2023-05-15 at 10 53 05](https://github.com/jensengroup/molcalc/assets/2011468/7a997592-f8f5-4add-8dda-503b3d282bff)

**Comment by fjvico** [comment]
OK, got it. Then this mean that 2D structures might represent different conformers.
