### ISSUE TITLE
Feature Request: support larger molecules

### ISSUE THREAD

**Issue by Kbomar925** [jensengroup/molcalc#42]
I was trying to use your amazing software to calculate a dipole moment for 2,2-bis(trifluoromethyl)-1,1-dicyanoethylene. The system blocked me due to the molecule having greater than 10 heavy atoms. I'm wondering if there is any way around this? I would be willing to pay. Perhaps have a paid version of the software that allowed for a greater tax on the servers would be useful to other users as well.

**Comment by charnley** [comment]
Hi @Kbomar925, sorry.

The MolCalc application is designed for teaching and is hosted on very small server. If you need quantum chemistry calculations on a molecule for industrial or research reasons, you should not be using MolCalc. The calculations are fast but can be quite inaccurate, especially on large molecules (PM3 and Hatree-Fock).

If it is the interface you need, I recommend that you download it and set it up yourself, then you can remove any restrictions.
