### ISSUE TITLE
Unable to Navigate to "Help" and "About" Page

### ISSUE THREAD

**Issue by SharanRP** [jensengroup/molcalc#43]
I wanted to bring to your attention an issue I encountered using the website Specifically, I'm having difficulty navigating to the "Help" and "About" pages within the application.

Upon attempting to access these pages , site keeps on loading . As a result, I'm unable to access important information and resources that may be available in these sections.

Could you please verify whether this issue is valid and whether others have reported similar problems? If it is indeed a bug or a usability issue, I would like to offer my assistance in addressing it.

@charnley @vladislavivanistsev

**Comment by charnley** [comment]
@SharanRP, it looks like the server died; I will restart it in a few hours.

**Comment by charnley** [comment]
@SharanRP. Thanks for reporting. The issue was the server was under heavy load with too many computations at the same time. It is resolved now, but feel free to write to open another issue if it happens again.

I want to avoid writing a queue system, but if this happens again I will do that.
