### ISSUE TITLE
Very often get error when trying to calculate

### ISSUE THREAD

**Issue by Argenteus-CG** [jensengroup/molcalc#9]
Occurs on not all, but many molecules. Error is as follows:

Warning: file_get_contents(http://cactus.nci.nih.gov/chemical/structure/%5BLi%5Dc1cc(F)c(F)c(F)c1/iupac_name) [function.file-get-contents]: failed to open stream: HTTP request failed! HTTP/1.1 404 NOT FOUND in /srv/www/molcalc/methods/initialize/initialize.php on line 53
7b4558bddc63c9a67a1e0c06fc2f6b51

**Comment by charnley** [comment]
Does it happen when you press "calculate properties"? or when does the bug accrue?

**Comment by Argenteus-CG** [comment]
Yes, sorry, I thought that was clear.

**Comment by charnley** [comment]
The error was from trying to get a name from smiles via the cactus server. Fixed in both live and development version.
